#!/bin/sh
# automated retrieval of pipermail archives & conversion to mbox file
# Last edit: 2012/10/09 Tue 23:16 PDT

# This scripts downloads a pipermail archive and converts it into a
# mbox file to be read by neomutt.
#
# NOTE: Remember the final slash!
# Usage: 
# 	piperget https://link/to/pipermail/archive/

set -x
mkdir -p /tmp/pipermail

listname=$(echo "$1" | sed 's:^\(http.*\)/\([^/]*\)/$:\2:')
cd /tmp
wget -r -l 1 -nH -A *.txt.gz "$1"
touch /tmp/pipermail/$listname/$listname.mbox
chmod 600 /tmp/pipermail/$listname/$listname.mbox
cd /tmp/pipermail/$listname
for f in $(ls |sort)
do zcat $f | iconv -f iso8859-15 -t utf-8 | sed 's/\(^From.*\)\ at\ /\1@/' >> "$listname.mbox"
done
rm /tmp/pipermail/$listname/*.gz
neomutt -f /tmp/pipermail/$listname/$listname.mbox
