#!/bin/sh
#
# Use notmuch hook to index the notmuch database using queries

notmuch tag -inbox +sent from:chrisbcoutinho@gmail.com
notmuch tag -inbox +sent from:cc162@humboldt.edu
notmuch tag -inbox +sent from:c.coutinho@redstack.nl
notmuch tag -inbox +sent from:ccoutinho@a-hak.nl

notmuch tag -inbox +cinemacephale cinema@acephale.eu
notmuch tag -inbox +dragonflybsd dragonflybsd.org
notmuch tag -inbox +freebsd freebsd.org
notmuch tag -inbox +github from:github.com or to:github.com
notmuch tag -inbox +paraview gitlab.kitware.com or paraview@public.kitware.com or paraview.org
notmuch tag -inbox +gitlab gitlab.com
notmuch tag -inbox +gnupg gnupg.org
notmuch tag -inbox +opensuse suse.org
notmuch tag -inbox +pass password-store
notmuch tag -inbox +python python.org
notmuch tag -inbox +rotaract rotaract

notmuch tag -inbox +dakota dakota-users@software.sandia.gov

notmuch tag -inbox +promotions unsubscribe
