#!/usr/bin/env bash

# A simple script to pull all software from git repositories in the
# $HOME/Software directory

# Show lines being run
#set -x

gitdirs=$( fd '\.git$' --absolute-path --hidden --type directory --max-depth 2 $HOME/Software --exec=dirname)
#gitdirs=$(find $HOME/Software -type d -execdir test -d {}/'.git' \; -prune -print)

for ii in $gitdirs; do
echo && echo $ii
git -C $ii fetch --all --tags
git -C $ii submodule update --init --recursive
git -C $ii pull --recurse-submodules
done
