#!/usr/bin/env bash

# A simple script to pull all software from git repositories in a
# specified directory

# If no input is supplied, use the Software directory
input=${1:-$HOME/Software}

#gitdirs=$( fd '\.git$' --absolute-path --hidden --type directory --max-depth 2 $input --exec dirname | sort)
gitdirs=$( find $input -maxdepth 2 -type d -name '.git' -exec dirname {} \; | sort)

for ii in $gitdirs; do
	echo && echo $ii
	git -C $ii fetch --all --tags --prune
	git -C $ii submodule update --init --recursive
	git -C $ii pull --ff-only --recurse-submodules
done
