# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    strategy:
      matrix:
        platform: [ubuntu-20.04, macos-latest]

    # The type of runner that the job will run on
    runs-on: ${{ matrix.platform }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Update apt-get cache if Linux
      run: command -v apt-get >/dev/null && sudo apt-get update || echo '-- apt-get not found'

    - name: Install packages
      run: command -v apt-get >/dev/null && sudo apt-get install neovim python3-setuptools python3-wheel zsh || echo '-- apt-get not found'

    # Runs a single command using the runners shell
    - name: Deploy script
      run: ./deploy.sh

    - name: Test if zsh works
      run: zsh --interactive -c 'echo Hello World'
